### PR TITLE
[CUB-4865] delay removed as not implemented

### PR DESCRIPTION
**Pull request by lo-ci-jared**
### Description
Delay commented out for behaviors as it is not implemented.

### Manual PR Checklist

- [x] All related Jira tickets added to PR title
- [x] Description in Jira ticket is clear and up-to-date

[CUB-4865]: https://labforward.atlassian.net/browse/CUB-4865?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by lo-ci-jared** [comment]
schemas need to be compiled, then the pull request can be moved out of draft and merged :-)

**Comment by kgrhartlage** [comment]
@lo-ci-jared thanks for opening the PR.

- Removed the comments, since it's not a given that the schema will be same if we do add support for delays.
- Removed a mention of "delay" in the description for behaviors.
- Updated the example templates to remove mentions of delay
- Change file suffix of fixture templates from "yaml" to "yml" for consistency

**Comment by lo-ci-jared** [comment]
Great - thanks, @kgrhartlage ! The PR is now published and can be merged. :-)

**Review by kgrhartlage — APPROVED** [review]
swamp-thing-thumbs-up-gif

**Pull request merged**
